name = "unitools"
compatibility_date = "2025-08-03"
main = "./src/index.tsx"

[[durable_objects.bindings]]
name = "UNITOOLS_EDITORS"
class_name = "YDurableObjects"

[[d1_databases]]
binding = "DB"
database_name = "unitools"
database_id = "REPLACE_WITH_DATABASE_ID"

[[migrations]]
tag = "v1"
new_classes = ["YDurableObjects"]

#:schema ./node_modules/wrangler/config-schema.json
