name = "unitools"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "./src/index.tsx"

[[durable_objects.bindings]]
name = "UNITOOLS_EDITORS"
class_name = "YDurableObjects"

[[d1_databases]]
binding = "DB"
database_name = "unitools"
database_id = "a77060bf-9808-4199-946a-bef359ebdc30"
migrations_dir = "./src/db/migrations"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "7d67dbf809c246b786db685c69b8bab1"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID"

[[r2_buckets]]
binding = "UNITOOLS_R2"
bucket_name = "unitools"

[[migrations]]
tag = "v1"
new_classes = ["YDurableObjects"]

#:schema ./node_modules/wrangler/config-schema.json
